FROM telegraf:1.37.0

# SNMP Tools installieren
RUN apt-get update && \
    apt-get install -y snmp && \
    rm -rf /var/lib/apt/lists/*

# MIB-Lookup komplett deaktivieren - nur numerische OIDs
RUN echo "mibs :" > /etc/snmp/snmp.conf

# SNMP Fehler unterdrücken
ENV MIBS=""
