---
services:
   minio:
     image: quay.io/minio/minio
     container_name: minio
     hostname: minio
     command: server /data --console-address ":9001"
     restart: "unless-stopped"
     ports:
       - "9000:9000/tcp"
       - "9001:9001"
     environment:
       - MINIO_ROOT_USER=admin
       - MINIO_ROOT_PASSWORD=Password
     volumes:
       - ${HOME}/minio/data:/data
